### ISSUE TITLE
[SSL certificate problem: certificate has expired]

### ISSUE THREAD

**Issue by habnai** [karljohns0n/nginx-more#45] opened 2024-06-05 19:02 UTC
can you fix this please i want use it in almalinux 9 but i get 
`root@server1 ~]# dnf install -y https://repo.aerisnetwork.com/pub/aeris-release-9.rpm
Last metadata expiration check: 0:21:43 ago on Wed Jun  5 20:34:42 2024.
[MIRROR] aeris-release-9.rpm: Curl error (60): SSL peer certificate or SSH remote key was not OK for https://repo.aerisnetwork.com/pub/aeris-release-9.rpm [SSL certificate problem: certificate has expired]
[MIRROR] aeris-release-9.rpm: Curl error (60): SSL peer certificate or SSH remote key was not OK for https://repo.aerisnetwork.com/pub/aeris-release-9.rpm [SSL certificate problem: certificate has expired]
[MIRROR] aeris-release-9.rpm: Curl error (60): SSL peer certificate or SSH remote key was not OK for https://repo.aerisnetwork.com/pub/aeris-release-9.rpm [SSL certificate problem: certificate has expired]
[MIRROR] aeris-release-9.rpm: Curl error (60): SSL peer certificate or SSH remote key was not OK for https://repo.aerisnetwork.com/pub/aeris-release-9.rpm [SSL certificate problem: certificate has expired]
[FAILED] aeris-release-9.rpm: Curl error (60): SSL peer certificate or SSH remote key was not OK for https://repo.aerisnetwork.com/pub/aeris-release-9.rpm [SSL certificate problem: certificate has expired]
Curl error (60): SSL peer certificate or SSH remote key was not OK for https://repo.aerisnetwork.com/pub/aeris-release-9.rpm [SSL certificate problem: certificate has expired]
[root@server1 ~]# dnf install -y https://repo.aerisnetwork.com/pub/aeris-release-9.rpm
`

**Comment by karljohns0n** [comment] 2024-06-05 19:06
Hello, thanks for the report, it's been fixed and the cause will be investigated!

**Closed by karljohns0n** 2024-06-05 19:06 UTC
